"""
rebalance_catalogue.py
------------------------
Fixes the catalogue energy skew diagnosed in the Draft Report
(Section 5.6): median track energy 0.64, only 10.3% of tracks below
energy 0.3, versus 41.4% above 0.7. That draft correctly identified
the cause of poor calm/low-energy adherence but only *planned* a fix
("sampling more low-energy tracks when the catalogue is next rebuilt").
This script does it.

Approach: re-uses build_catalog.py's genre-sampling machinery, but
targets genres/energy bands under-represented in the current
catalogue instead of sampling top-N-by-popularity per genre
regardless of energy. Classical, acoustic, and jazz already skew calm
in the existing catalogue (see track_catalog.py) -- this samples
MORE from exactly those genres, filtered explicitly by energy < 0.35,
rather than by raw popularity, which is what caused the original skew
(the most popular tracks in any genre tend to be higher-energy).

Usage (same working directory as build_catalog.py, with the same
Kaggle CSV available):
    python rebalance_catalogue.py spotify_tracks_dataset.csv

Output:
    low_energy_additions.py -- TRACK_CATALOG-format entries to append
    to track_catalog.py (run fetch_tags.py and add_spotify_ids.py on
    the merged file afterward, same as any other catalogue update).
"""

import csv
import sys
import os

_HERE = os.path.dirname(os.path.abspath(__file__))

TARGET_GENRES = ["classical", "acoustic", "folk", "jazz", "ambient", "sleep", "study"]
ENERGY_CEILING = 0.35
TRACKS_PER_GENRE = 8
START_ID = 200  # first free id after t001-t179 in the current catalogue


def norm(s):
    return "".join(c for c in s.lower() if c.isalnum() or c.isspace()).strip()


def load_rows(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def pop_of(row):
    try:
        return float(row.get("popularity", 0))
    except (TypeError, ValueError):
        return 0.0


def fmt_row(tid, row):
    tempo = round(float(row["tempo"]), 1)
    energy = round(float(row["energy"]), 2)
    valence = round(float(row["valence"]), 2)
    popularity = round(pop_of(row) / 100.0, 2)
    title = row["track_name"].replace('"', '\\"')
    artist = row["artists"].split(";")[0].replace('"', '\\"')
    genre = row.get("track_genre", "")
    return (f'    {{"id": "{tid}", "title": "{title}", "artist": "{artist}", '
            f'"tempo": {tempo}, "energy": {energy}, "valence": {valence}, '
            f'"popularity": {popularity}, "genre_hint": "{genre}"}},')


def main():
    if len(sys.argv) != 2:
        print("Usage: python rebalance_catalogue.py <spotify_tracks_dataset.csv>")
        sys.exit(1)

    rows = load_rows(sys.argv[1])
    by_genre = {}
    for r in rows:
        by_genre.setdefault(r["track_genre"], []).append(r)

    picked = []
    next_id = START_ID
    seen_keys = set()

    for genre in TARGET_GENRES:
        pool = [r for r in by_genre.get(genre, []) if float(r.get("energy", 1)) < ENERGY_CEILING]
        # Sort candidates within the energy-filtered pool by popularity
        # (not the other way around) -- energy is the hard filter here,
        # popularity only breaks ties among tracks that already qualify.
        pool.sort(key=pop_of, reverse=True)
        added = 0
        for r in pool:
            key = norm(r["artists"].split(";")[0]) + "::" + norm(r["track_name"])
            if key in seen_keys or added >= TRACKS_PER_GENRE:
                continue
            seen_keys.add(key)
            picked.append((f"t{next_id:03d}", r))
            next_id += 1
            added += 1
        print(f"{genre}: found {len(pool)} tracks with energy < {ENERGY_CEILING}, added {added}")

    if not picked:
        print("\nNo matching genres found in this dataset's track_genre "
              "values -- print sorted(set(r['track_genre'] for r in rows)) "
              "to see what's actually available and adjust TARGET_GENRES.")
        return

    with open(os.path.join(_HERE, "low_energy_additions.py"), "w", encoding="utf-8") as out:
        out.write("# Auto-generated by rebalance_catalogue.py\n")
        out.write(f"# {len(picked)} tracks, all with energy < {ENERGY_CEILING}, "
                   f"appended to fix the energy skew diagnosed in Draft Report Section 5.6.\n")
        out.write("LOW_ENERGY_ADDITIONS = [\n")
        for tid, row in picked:
            out.write(fmt_row(tid, row) + "\n")
        out.write("]\n")

    print(f"\nWrote low_energy_additions.py with {len(picked)} new low-energy tracks.")
    print("Next: merge LOW_ENERGY_ADDITIONS into TRACK_CATALOG in track_catalog.py, "
          "re-run fetch_tags.py and add_spotify_ids.py for just the new ids, "
          "then re-run evaluation.evaluate.catalogue_energy_distribution_eval() "
          "and mood_adherence_eval() to confirm the skew and the adherence gap "
          "both improved -- report the before/after numbers directly.")


if __name__ == "__main__":
    main()
